# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - manicustomerservicedockerapp1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://manimyregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_318f92205509426f8aa83b8a6bb1cfc1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2410eb696357426dbc09541254c11c1d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: manimyregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_318f92205509426f8aa83b8a6bb1cfc1 }}/spring-boot-2-rest-service-swagger:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'manicustomerservicedockerapp1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3540f1acd3fa4e8fa3ff94928b8aae40 }}
        images: 'manimyregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_318f92205509426f8aa83b8a6bb1cfc1 }}/spring-boot-2-rest-service-swagger:${{ github.sha }}'